### PR TITLE
Build 1 of 0.4.10: pin python>=3.9

### PR DESCRIPTION
**Pull request by maximlt**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

spatialpandas 0.4.10 dropped support of Python 3.8 and I forgot to pin `python >=3.9` in this release.

### CODE REVIEW

**Comment by ianthomas23** [comment]
Hi @maximlt. Could you remove my name from the list of `recipe-maintainers` at the bottom of the `meta.yaml`?

**Comment by maximlt** [comment]
> Hi @maximlt. Could you remove my name from the list of `recipe-maintainers` at the bottom of the `meta.yaml`?

Sure! Done in https://github.com/conda-forge/spatialpandas-feedstock/pull/18/commits/587850c37b5fa0a3db45373e6241c2f051a73a12

**Comment by ianthomas23** [comment]
> Sure! Done in [587850c](https://github.com/conda-forge/spatialpandas-feedstock/commit/587850c37b5fa0a3db45373e6241c2f051a73a12)

Thanks! :smiley:

**Comment by maximlt** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
